### ISSUE TITLE
fftshift/ifftshift

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/AbstractFFTs.jl#1]
There should be tests for fftshift, ifftshift Base, and these should be documented and exported.

**Comment by ararslan** [comment]
They are both documented and exported: https://github.com/JuliaMath/AbstractFFTs.jl/blob/master/src/AbstractFFTs.jl#L361

**Comment by stevengj** [comment]
Ah, I missed that export.  I meant documented in the README, not just in the docstring.  And they still need tests.

**Comment by ararslan** [comment]
Everything still needs tests at this point. 😛

**Comment by stevengj** [comment]
Yes, but these functions already have tests in Base, which just need to be copied over.
