### ISSUE TITLE
Frequencies of FFT: `fftfreq`

### ISSUE THREAD

**Issue by crstnbr** [JuliaMath/AbstractFFTs.jl#19]
I think it would make sense to add a `fftfreq` function here which returns the discrete FFT sample frequencies. Currently, a version is provided by DSP.jl [here](https://github.com/JuliaDSP/DSP.jl/blob/920480c90975d6cc7eb5b2e3e95f468dbf55e640/src/util.jl#L146). It seems odd that one has to add another package for getting the FFT frequencies.

Note that numpy [also has this](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fftfreq.html) as part of `numpy.fft`.

I could make a PR. What do you think?

**Comment by heitorPB** [comment]
I was also looking for a `fftfreq` as well...

You still interested in making a PR?

**Comment by crstnbr** [comment]
This is still on my list but with low priority. I don't know when I'll find the time. So if you want to take care of it feel free to do so!
