### ISSUE TITLE
fft(A) seems broken?

### ISSUE THREAD

**Issue by Datseris** [JuliaMath/AbstractFFTs.jl#21]
```julia
julia> fft(rand(500, 500))
ERROR: MethodError: no method matching plan_fft(::Array{Complex{Float64},2}, ::UnitRange{Int64})
Closest candidates are:
  plan_fft(::AbstractArray{#s16,N} where N where #s16<:Real, ::Any; kws...) at
C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:199
  plan_fft(::AbstractArray{#s25,N} where N where #s25<:(Complex{#s26} where #s26<:Union{Integer, Rational}), ::Any; kws...) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:201
  plan_fft(::AbstractArray; kws...) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:52
Stacktrace:
 [1] fft(::Array{Complex{Float64},2}, ::UnitRange{Int64}) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:51
 [2] fft(::Array{Float64,2}, ::UnitRange{Int64}) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:198 (repeats 2 times)
 [3] top-level scope at none:0

julia> fft(rand(100))
ERROR: MethodError: no method matching plan_fft(::Array{Complex{Float64},1}, ::UnitRange{Int64})
Closest candidates are:
  plan_fft(::AbstractArray{#s16,N} where N where #s16<:Real, ::Any; kws...) at
C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:199
  plan_fft(::AbstractArray{#s25,N} where N where #s25<:(Complex{#s26} where #s26<:Union{Integer, Rational}), ::Any; kws...) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:201
  plan_fft(::AbstractArray; kws...) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:52
Stacktrace:
 [1] fft(::Array{Complex{Float64},1}, ::UnitRange{Int64}) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:51
 [2] fft(::Array{Float64,1}, ::UnitRange{Int64}) at C:\Users\datseris\.julia\packages\AbstractFFTs\7WCaR\src\definitions.jl:198 (repeats 2 times)
 [3] top-level scope at none:0
```

I am not sure what I am doing wrong, but the docs suggest this is how I should be using `fft`.

**Comment by Datseris** [comment]
For version:
```
  [621f4979] + AbstractFFTs v0.3.2
```

**Comment by stevengj** [comment]
It's not broken.  The AbstractFFTs package does not provide any FFT implementations.  You need a package like FFTW.jl that's built on top of AbstractFFTs.

**Comment by Datseris** [comment]
This is very unintuitive. The documentation of AbstractFFTs lists a function `fft`. The documentation of the function describes exactly what an fft does, so naturally I would try to use it. Moreover, going into the docs of FFTW, I read:


> This package **extends** the functionality provided by AbstractFFTs. To learn more about those functions, > consult that package's documentation.

(I stressed extend) Continuing on that page, you see the functions `r2r` and `dct` stated as the public API. By this it becomes clear that these are the functions offered by FFTW and nothing else.

Then, the question is, which package actually implements `fft(Matrix)` ? Well, after reading your comment here, I imagine it should be FFTW.

And indeed:
```julia
julia> using FFTW

julia> fft(rand(100,100))
100×100 Array{Complex{Float64},2}:
  5074.28+0.0im       …   -0.323417-51.1534im
 -23.8656-5.88582im        -23.0815-20.4755im
  21.1678+15.6159im        -5.79701+8.31932im
```

I don't know why this decision has been made, it probably has a bunch of reasons, but for me as a user and not a developer of FFTW the functions `fft`, etc. etc. should be listed properly in FFTW's documentation. From my perspective as a user and not a developer they do not _extend_ something, they implement it.

In fact the entire existence of `AbstractFFTs` is now confusing me. I was originally searching for the plain-ol' 2D fourier transform. It was not in base anymore. I googled and found FFTW and read its documentation. I naturally deduced that a standard `fft` is not there as it is not listed in its API. I then find `AbstractFFTs` which does list `fft` in its documentation. But turns out the algorithm is not there. It is in FFTW.

This is very confusing, I hope you can see my point.

**Comment by stevengj** [comment]
The first line of the README is "This package is mainly not intended to be used directly."
