### ISSUE TITLE
Documentation "broken" since v.4.0

### ISSUE THREAD

**Issue by crstnbr** [JuliaMath/AbstractFFTs.jl#23]
Compare

https://juliamath.github.io/AbstractFFTs.jl/v0.3/api.html#Public-Interface-1 (v0.3)

to the current

https://juliamath.github.io/AbstractFFTs.jl/v0.4/api/#Public-Interface-1 (v0.4).

Even the definition of the FFT isn't displayed anymore!

**Comment by ararslan** [comment]
Apparently the fix is to update the Documenter version in docs/Project.toml to 0.22.0 and to address this warning: https://travis-ci.org/JuliaMath/AbstractFFTs.jl/jobs/519735150#L475.
