### ISSUE TITLE
With Double64s?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/AbstractFFTs.jl#27]
There is a [request](https://github.com/JuliaMath/DoubleFloats.jl/issues/74) for FFT support through DoubleFloats.  I read the information on what AbstractFFTs requires of a number type.
Are there any respectable unnormalized backwards FFT implementations written in Julia for AbstractFloats?

**Comment by stevengj** [comment]
JuliaApproximation/FastTransforms.jl#64 implemented one, I believe.

I also implemented my own native-Julia FFT at one point that supported arbitrary precision (JuliaLang/julia#6193), but never got around to polishing it.
