### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by galenlynch** [JuliaMath/AbstractFFTs.jl#30]
Now that #26 has been merged, it would be great if someone could tag a new version of AbstractFFTs.jl to reduce the breakage that #26 causes in DSP.jl.

**Comment by crstnbr** [comment]
bump

**Comment by crstnbr** [comment]
bump, again

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/5220
