### ISSUE TITLE
Roadmap to 1.0?

### ISSUE THREAD

**Issue by oxinabox** [JuliaMath/AbstractFFTs.jl#47]
What is left before this can be tagged as 1.0?

**Comment by stevengj** [comment]
If we add a ChainRulesCore dependency, then I think it would be fine to tag it as 1.0.

**Comment by oxinabox** [comment]
Depending on ChainRulesCore is a non-breaking change.
so it is probably fine to tag 1.0 right now.

**Comment by dlfivefifty** [comment]
Close this issue?
