### ISSUE TITLE
plan_* should be moved to FFTW.jl

### ISSUE THREAD

**Issue by appleparan** [JuliaMath/AbstractFFTs.jl#8]
It seems `AbstractFFTs.jl` is still not separated with `FFTW.jl` . `plan_*` are from `FFTW` library. It seems weird because plans are still in `AbstractFFTs.jl` and most of implementation are at `FFTW.jl`.

Why not moving plans to FFTW.jl?

**Comment by appleparan** [comment]
I got a response from @ararslan 
"The plans in AbstractFFTs are implemented in Julia, whereas the plans in FFTW call the FFTW C library. AbstractFFTs is the more general package, containing a framework for other FFT packages to build on."

I close it.

**Comment by stevengj** [comment]
Yes, non-FFTW implementations of FFTs may want to use the `plan_fft` interface.

**Comment by appleparan** [comment]
However, I think some of docs should be moved to `FFTW.jl`. For example, doc about [plan_fft](https://juliamath.github.io/AbstractFFTs.jl/latest/api.html#AbstractFFTs.plan_fft) uses FFTW's constants such as `FFTW.MEASURE` or `FFTW.PATIENT`. I now understand why `FFTW.jl` and `AbstractFFTs.jl` are separated but docs may be confusing to new users because some of actual implementation resides in `FFTW.jl`
